### ISSUE TITLE
Checklist items in readme.md

### ISSUE THREAD

**Issue by jamerrq** [linuxmobile/midu.dev#9]
**Descripción**
Hace falta poner un espacio en los checklists (y organizarlos en lista) de la sección `Roadmap` markdown para que aparezcan de manera correpta en la descripción

**Comportamiento esperado**
Una lista de checboxes así
- [ ] Mobile responsive.
- [ ] 100/100 Lighthouse performance.
- [ ] SEO-friendly with canonical URLs and OpenGraph data.
- [ ] Sitemap support.
- [ ] RSS Feed support.
- [ ] Image optimization.
- [ ] Light mode.
- [ ] Draft mode.
- [ ] Copy code block.
- [ ] Post Sharing Options.
<br />

- [ ] Página de Agenda.
- [ ] Sección Redes Sociales (home).
- [ ] Sección últimas clases.

**Comportamiento actual**
![image](https://github.com/linuxmobile/midu.dev/assets/35697365/641ace5b-e30d-42c6-af17-c2bb0e2fe1c4)

**Comment by jamerrq** [comment]
En caso tal, yo mismo podría arreglarlo @linuxmobile , es muy sencillo!

**Comment by linuxmobile** [comment]
> En caso tal, yo mismo podría arreglarlo @linuxmobile , es muy sencillo!

Gracias! Espero la PR <3
